Instagram-master/config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/new'
  get 'posts/update'
  get 'posts/delete'
  match "/contact", to: "pages#contact", via: :get
  get "/about", to: "pages#about"
  root "pages#index"
  resources :users
 
  #resources :sessions, only: [:new,:create,:destroy]
  get "/login", to: "sessions#new"
   get "/signup", to: "users#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :posts, only: [:create, :destroy]
  resources :likes, only: [:create]
  delete "/unlike", to: "likes#destroy"

end

Instagram-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Instagram-master/app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

Instagram-master/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  body        :text
#  user_id     :integer
#  likes_count :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ApplicationRecord
	validates :body, length: {maximum: 255}
	validates :user_id, presence: true
	belongs_to :user
	has_one_attached :image
	has_many :likes

	default_scope -> {order "created_at DESC"}
	

	def liked?
		if signed_in?
			likes.where(user_id: current_user.id).count > 0
		end
	end
end

Instagram-master/app/models/user.rb
class User < ApplicationRecord
    has_secure_password

	has_many_attached :posts
    has_one_attached :avatar
    validates_presence_of :email, :username
    validates_uniqueness_of :email, :username
    validates :password, length: {minimum: 6, maximum: 39}
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :update

    #validates_format_of :email, message: 'The e-mail format is not correct!'
    validates :username, :password, format: { with: /\A[0-9a-zA-Z_.\- ]+\Z/, message: "Only alphanumeric characters, spaces and -_."}
    validates :username, length: {maximum: 30}

    before_create {self.email = email.downcase}
	before_create {self.username = username.downcase}

    attr_accessor :remember_token
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns the hash digest of the given string.
	def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

  # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end
      # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
        if remember_digest.nil?
            false
        else
            BCrypt::Password.new(remember_digest).is_password?(remember_token)
        end
  end
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

Instagram-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

Instagram-master/app/controllers/likes_controller.rb
class LikesController < ApplicationController
	
	def create
		respond_to do |format|
			format.html {}
			format.js {}
		end
	end

	def destroy
	end
end

Instagram-master/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	if signed_in?
		  @feed = current_user.posts
      @post = Post.new
  	end
  end

  def about
  end

  def contact
  end
end

Instagram-master/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :check, only: :destroy

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else
      render "pages#new"
    end
  end

  def destroy

    Post.find(params[:id]).destroy!
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:body, :image)
  end

  def check
    unless current_user && Post.find(params[:id]).user_id == current_user.id
      flash[:danger] = "Not your post!"
      redirect_to root_path
    end
  end


end

Instagram-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create 
		login = params[:session][:login]
		if login.include? "@"
			user = User.find_by_email(login)
		else
			user = User.find_by_username(login)
		end
    if user && user.authenticate(params[:session][:password])
      sign_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user

		else
			flash.now[:danger] = "Invalid email/password combination"
      		render 'new'
		end
	end

	def new 
	end

	def destroy 
		sign_out if signed_in?
		redirect_to root_path
	end
end

Instagram-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new

	end

	def create
		@user  = User.new(user_params)
		if @user.save
			sign_in @user
			redirect_to @user
		else
			render :new
		end

	end

	def edit
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user 
		else
			render 'edit'
		end
	end
	
	def destroy
	    user = User.find(params[:id])
	    sign_out if signed_in?
	    @user = user.destroy
			redirect_to users_url
	end
	
	def user_params 
		params.require(:user).permit(:username, :email,:password, :avatar)
	end

end

Instagram-master/app/helpers/application_helper.rb
module ApplicationHelper
end

Instagram-master/app/helpers/likes_helper.rb
module LikesHelper
end

Instagram-master/app/helpers/pages_helper.rb
module PagesHelper
	def pretty_title(title)
		#"| " + title unless title.nil? 
		title.nil? ? "Instagram " : "| " + title
	end
end

Instagram-master/app/helpers/posts_helper.rb
module PostsHelper
end

Instagram-master/app/helpers/sessions_helper.rb
module SessionsHelper


	def sign_in(user)
		session[:user_id] = user.id
	end


	def signed_in?
		!current_user.nil?

	end
	 # Remembers a user in a persistent session.


	  def remember(user)
	    user.remember
	    cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token
	  end


	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find(session[:user_id])
		 elsif (user_id = cookies.signed[:user_id])
    		user = User.find_by(id: user_id)
    		if user && user.authenticated?(cookies[:remember_token])
    			sign_in user
    			@current_user = user
    		end
		end
	end
	 # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
	def sign_out
		forget(current_user)
		session[:user_id] = nil
		@current_user = nil
	end

end

Instagram-master/app/helpers/users_helper.rb
module UsersHelper
end

Instagram-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= pretty_title(@title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/header" %>

    <div class="container">
      <%= render "partials/errors" %>
      <%= yield %>
    </div>
  </body>
</html>

Instagram-master/app/views/likes/_likes.html.erb
<% if signed_in? %>
	<% if post.liked? %>
		<%= link_to unlike_path, method: :delete do %>
			<i class="far fa-heart">
		<% end %>

	<% else %>
		<%= link_to likes_path, remote: true do %>
			<i class="far fa-heart">
		<% end %>
	<% end %>
<% else %>
	<i class="far fa-heart"></i> <%= post.likes_count %>
<% end %>

Instagram-master/app/views/likes/create.js.erb
alert();

Instagram-master/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

Instagram-master/app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

Instagram-master/app/views/pages/index.html.erb
<% @title = "Homepage"%>



<%if signed_in?%>
 
	<div class="row">
		<div class="col-md-3">
			<% if current_user.avatar.attachment %>
				<%= image_tag current_user.avatar, height: 50 %>
				<%= link_to "edit", edit_user_path(current_user) %>
  				 <%= link_to "delete", current_user, method: :delete, data: { confirm: "Are you sure?" } %>
			<% end %>

		
				<%= form_for @post do |f| %>
					<div class="form-group">
						<%= f.text_area :body, class: "form-control" %>
					</div>
					<div class="form-group">
						<%= f.file_field :image, class: "form-control" %>
					</div>
					<%= f.submit :submit, class: "btn btn-outline-success" %>
				<% end %>
		</div>


		<div class="col-md-9">
			<%= render @feed %>
		</div>

	</div>

<% else %>
	<div class="jumbotron">
		<h1>Welcome to Intagram!</h1>
		<%= link_to "Sign in", login_path, class: "btn btn-primary" %> 
		<%= link_to "Register", signup_path, class: "btn btn-outline-info" %>
	</div>
<% end %>

Instagram-master/app/views/partials/_errors.html.erb
<% unless flash.empty? %>
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key%>">
			<%= value %>
		</div>
	<% end %>
<% end %>

Instagram-master/app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">Instagram</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/about">About</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/contact">Contact</a>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <%if signed_in? %>
        <li>
          
        
          <%= link_to "logout", logout_path, method: :delete, data: { confirm: "Are you sure?"} %></li>
          <%else%>
          <li>
          <%= link_to "login", login_path %></li>
          

      </li>
      <%end%>
    
  </ul>

  </div>
  </div>

</nav>


     

Instagram-master/app/views/posts/_post.html.erb
<div class="well">
	<% if post.image.attachment %>
		<%= image_tag post.image, class: "img-fluid img-thumbnail" %>
	<% end %>
	<p><%= post.body %></p> 
	
	<%= link_to "Delete", post, method: :delete, data: {confirm: "U sure?"} %>
</div>

Instagram-master/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update user profile</h1>
<%= form_for @user do |f| %>
<% if @user.errors %>
<ul>
    <% @user.errors.full_messages.each do |m| %>
    <li><%= m %></li>
    <% end %> 
</ul>
    <% end %>

<%= f.text_field :username, placeholder: "new username" %>
<%= f.text_field :email, placeholder: "new email" %>
<%= f.password_field :password, placeholder: "new password" %>
<%= f.file_field :avatar%>
<%= f.submit :submit %>

<% end %>

Instagram-master/app/views/users/index.html.erb
<ul>

	<% @users.each do |user| %>
	<li><%= link_to user.username, "/users/#{user.id}" %></li>
	<li><%= link_to "edit", edit_user_path(current_user) %></li>
	<li><%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Are you sure?" } %></li>

	<% end %>
	
</ul>

Instagram-master/app/views/users/new.html.erb
<%= form_for @user do |f| %>
<% if @user.errors %>
<ul>
    <% @user.errors.full_messages.each do |m| %>
    <li><%= m %></li>
    <% end %>
</ul>
    <% end %>

<%= f.text_field :username, placeholder: "username" %>
<%= f.text_field :email, placeholder: "email" %>
<%= f.password_field :password, placeholder: "password" %>
<%= f.file_field :avatar%>
<%= f.submit :submit %>

<% end %>

Instagram-master/app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h2><%= @user.email %></h2>

<% if @user.avatar.attachment.nil? %>
	<img src="https://www.bsn.eu/wp-content/uploads/2016/12/user-icon-image-placeholder-300-grey.jpg">

<% else %>
	<%= image_tag @user.avatar %>
	
<% end %>